dist: trusty
language: python
cache:
  pip: true
  directories:
  - packages
  - tests/cache
  - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: 3.4
    - os: linux
      sudo: required
      language: python
      python: 3.5
    - os: linux
      sudo: required
      language: python
      python: 3.6
    - os: osx
      osx_image: xcode8
      language: generic

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash .travis/linux_before_install.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash .travis/osx_before_install.sh ; fi

install:
- pip3 install .
- pip3 install -r requirements.txt -r test_requirements.txt

script:
- mv ocrmypdf dont_import_this_ocrmypdf
- pytest
- mv dont_import_this_ocrmypdf ocrmypdf

# See https://www.appneta.com/blog/pypi-deployment-with-travis-ci/ for
# steps to set up testpypi deploy for untagged builds if desired

deploy:
  provider: pypi
  user: ocrmypdf-travis
  password:
    secure: DTFOmmNL6olA0+yXvp4u9jXZlZeqrJsJ0526jzqf4a3gZ6jnGTq5UI6WzRsslSyoMMfXKtHQebqHM6ogSgCZinyZ3ufHJo8fn9brxbEc2gsiWkbj5o3bGwdWMT1vNNE7XW0VCpw87rZ1EEwjl4FJHFudMlPR1yfU5+uq0k0PACo=
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == "3.6" && $TRAVIS_OS_NAME == "linux"
  skip_upload_docs: true
