sudo: required
dist: trusty
language: python

cache: pip

cache:
    directories:
        - $HOME/.ccache
        - packages
        - tests/cache

python:
    - "3.4"
    - "3.5"
    - "3.6-dev"  # 3.6 not available yet

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
    # Ubuntu packages
    - sudo add-apt-repository ppa:vshn/ghostscript -y  # for ghostscript 9.16 (trusty has 9.10)
    - sudo add-apt-repository ppa:heyarje/libav-11 -y  # for libav11, which is for unpaper
    - sudo apt-get update -qq  # must go after all add-apt-repo
    - sudo apt-get install -y ghostscript tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng tesseract-ocr-fra qpdf poppler-utils libavformat56 libavcodec56 libavutil54 libffi-dev

    # pip
    - pip install --upgrade pip

    # Download, make and install unpaper (using ccache)
    - mkdir -p packages
    - "[ -f packages/unpaper_6.1-1.deb ] || wget -q https://dl.dropboxusercontent.com/u/28971240/unpaper_6.1-1.deb -O packages/unpaper_6.1-1.deb"
    - sudo dpkg -i packages/unpaper_6.1-1.deb

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python setup.py clean
    - python setup.py install
    - python setup.py test

os:
    - linux
