branches:
  except:
    - azure

cache:
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      env:
        - DIST=trusty
        - MINIMAL=true
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:alex-p/tesseract-ocr"
            - sourceline: "ppa:vshn/ghostscript"
          packages:
            - ghostscript
            - libffi-dev
            - tesseract-ocr
            - tesseract-ocr-deu
            - tesseract-ocr-eng
            - tesseract-ocr-fra
      before_install: |
        pip3 install --upgrade pip
        pip3 install --upgrade wheel
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      env:
        - DIST=trusty
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:alex-p/tesseract-ocr"
            - sourceline: "ppa:heyarje/libav-11"
            - sourceline: "ppa:vshn/ghostscript"
          packages:
            - ghostscript
            - libavcodec56
            - libavformat56
            - libavutil54
            - libffi-dev
            - tesseract-ocr
            - tesseract-ocr-deu
            - tesseract-ocr-eng
            - tesseract-ocr-fra
            - libexempi3 # --- optional extras from here ---
            - pngquant
            - poppler-utils
      before_install: |
        mkdir -p bin packages
        pip3 install --upgrade pip
        pip3 install --upgrade wheel
    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: "3.7"
      env:
        - DIST=xenial
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:alex-p/tesseract-ocr"
          packages:
            - ghostscript
            - libexempi3
            - libffi-dev
            - pngquant
            - poppler-utils
            - tesseract-ocr
            - tesseract-ocr-deu
            - tesseract-ocr-eng
            - tesseract-ocr-fra
            - unpaper
    - os: linux
      dist: bionic
      sudo: required
      language: python
      python: "3.8"
      env:
        - DIST=bionic
      addons:
        apt:
          update: true
          sources:
            - sourceline: "ppa:alex-p/tesseract-ocr"
          packages:
            - ghostscript
            - libexempi3
            - libffi-dev
            - pngquant
            - poppler-utils
            - tesseract-ocr
            - tesseract-ocr-deu
            - tesseract-ocr-eng
            - tesseract-ocr-fra
            - unpaper
    - os: osx
      language: generic
      addons:
        homebrew:
          update: true
          packages:
            - exempi
            - ghostscript
            - jbig2enc
            - leptonica
            - openjpeg
            - pngquant
            - python
            - qpdf
            - tesseract
            - unpaper
      before_install: |
        pip3 install --upgrade pip
        pip3 install wheel

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - mkdir -p bin
  - export PATH=$PWD/bin:$PATH
  - pip3 install -r requirements/main.txt -r requirements/test.txt .

script:
  - tesseract --version
  - pytest -n auto
# deploy:
#   # release for main pypi
#   # 3.7 is considered the build leader and does the deploy, otherwise there is
#   # a race and all versions will try to deploy
#   # OTOH if we ever need separate binary wheels then each version needs its
#   # own deploy
#   - provider: pypi
#     user: ocrmypdf-travis
#     password:
#       secure: "DTFOmmNL6olA0+yXvp4u9jXZlZeqrJsJ0526jzqf4a3gZ6jnGTq5UI6WzRsslSyoMMfXKtHQebqHM6ogSgCZinyZ3ufHJo8fn9brxbEc2gsiWkbj5o3bGwdWMT1vNNE7XW0VCpw87rZ1EEwjl4FJHFudMlPR1yfU5+uq0k0PACo="
#     distributions: "sdist bdist_wheel"
#     on:
#       branch: master
#       tags: true
#       condition: $TRAVIS_PYTHON_VERSION == "3.7" && $TRAVIS_OS_NAME == "linux"
#     skip_upload_docs: true
